// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/mao/tzgsdb/client/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/mao/tzgsdb/client/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/home/mao/tzgsdb/client/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProjectOutlined from '/home/mao/tzgsdb/client/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProjectOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined, ProjectOutlined };
